---
- name: Update APT Packages
  hosts: 192.168.5.24
  become: true  # This enables privilege escalation (sudo)
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade APT packages
      apt:
        upgrade: safe
        autoremove: yes
        autoclean: yes
